### ISSUE TITLE
Update REAMDE w/ ENV mode commands instructions

### ISSUE THREAD

**Issue by franswan** [boringprotocol/websitev2#14]

**Comment by redmanbravemm** [comment]
`yarn dev` and `yarn build` remain the same as defined before, as the ENV modes [are included ](https://github.com/boringprotocol/websitev2/pull/13/commits/da4f2d43127bf76b61418cecf21bc84d9d2545fe#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R20)within the node scripts.

I did update the README file a bit and added `ELEVENTY_ENV` as a note.

**Comment by franswan** [comment]
Sorry I missed that pull request. :) 

Closed!
