### ISSUE TITLE
Switch to Sass - No, Tailwind ! :)

### ISSUE THREAD

**Issue by redmanbravemm** [boringprotocol/websitev2#18]
Switch to Sass instead of stylus and include Tachyons as Sass too.

**Comment by franswan** [comment]
While we still ought to throw Stylus out. I'm considering we use Tailwind in place of the Tachyons/Sass approach we've been discussing. 

I've made a Tailwind branch but have not yet applied classes as the Tachyons/Stylus are still in place too.

**Comment by redmanbravemm** [comment]
Tailwind looks like a more solid, up-to-date choice, compared to Tachyons.

I've noticed you didn't pushed the branch yet, I might know the reasons. :) Apparently there's quite a lot of work involved here, as there are already some pages where Tachyons classes are already applied.

So the hard work here is to replace the Tachyons+stylus with Tailwind CSS -  [as a PostCSS plugin](https://tailwindcss.com/docs/installation#installing-tailwind-css-as-a-post-css-plugin) - then update/redo all the page styles using Tailwind :)

**Comment by franswan** [comment]
Yes sir, lol. I'll go ahead and push what I've done so far... It presently has Stylus and Tachyons (hooked up) but also is a start on integrating Tailwind...

**Comment by franswan** [comment]
https://github.com/boringprotocol/websitev2/tree/tailwind

**Comment by franswan** [comment]
> So the hard work here is to replace the Tachyons+stylus with Tailwind CSS - [as a PostCSS plugin](https://tailwindcss.com/docs/installation#installing-tailwind-css-as-a-post-css-plugin) - then update/redo all the page styles using Tailwind :)

The Tailwind equivalents per each Tachyon's class should be easy enough to swap out... The custom CSS that Stylus handled will need to be dealt with. I know Tailwind variables can handle much of that and we could do entirely without Sass but I'm not positive that we will not benefit from a Sass layer... We shall see if we need/want it...

**Comment by redmanbravemm** [comment]
Agree, first of all we need to learn the Tailwind way of doing CSS.
So. Many. Classes. 😵‍

![image](https://user-images.githubusercontent.com/88066581/129609848-2bc53520-108e-4dfc-9cfe-7b8ffb9636ce.png)

**Comment by franswan** [comment]
:) Existing component libraries will help us grab the essentials. Class audits and we can minimize any bloat by maintaining a strict style-guide... It's a dangerous amount of power we wield now!!!
