### ISSUE TITLE
Hook up Google Analytics 

### ISSUE THREAD

**Issue by franswan** [boringprotocol/websitev2#3]

**Comment by redmanbravemm** [comment]
Should we add the Analytics tracking code via Google Tag Manager?

**Comment by franswan** [comment]
> Should we add the Analytics tracking code via Google Tag Manager?
> Either way, we kinda need the user ID/container ID for Analytics/GTM.

Let me add you to the Analytics account when I can get your email privately. Let me add you to the Analytics account when I can get your email privately.

**Comment by franswan** [comment]
2506dd00fe9584b9e508764c32dab180e4ef7db5
This should suffice but I'll keep this issue open so it can be resisted before a site launch.

**Comment by redmanbravemm** [comment]
I was thinking maybe we should somehow exclude the Analytics tracking code when not in production/build mode.
This way we might avoid false Analytics logs. 🤔

**Comment by franswan** [comment]
Good point. I'll just comment that block out for now as there isn't any production branch yet.

**Comment by franswan** [comment]
Well actually will leave it for just a little while to test the setup is working properly. Nobody is really hitting this URL yet except for a few us builders.

**Comment by franswan** [comment]
> I was thinking maybe we should somehow exclude the Analytics tracking code when not in production/build mode.
> This way we might avoid false Analytics logs. 🤔

Ah, but more accurately to your point, we should put a conditional in the code for dev/build modes anyway....

**Comment by redmanbravemm** [comment]
Yes, we need something like `process.env.NODE_ENV` to test for dev/build modes,e g. for Analytics.

I guess we could update the package.json to contain both:
`NODE_ENV=development yarn dev`
`NODE_ENV=production yarn build`

Not at my laptop now, but this should work afaik.

**Comment by redmanbravemm** [comment]
I managed to test the above approach and reached to a clean solution in my opinion #13

The nice thing is that the default scripts do not change, so we'll further be able to use the same `yarn dev` and `yarn build`.

**Comment by redmanbravemm** [comment]
@franswan I think we could close this issue
